import { Router } from "express";
import auth from "../middleware/authMiddleware.js";
import { uploadAvatar } from "../middleware/uploadMiddleware.js";
import * as controller from "../controllers/userController.js";

const router = Router();
router.use(auth);
router.get("/profile", controller.profile);
router.put("/profile", controller.updateProfile);
router.post("/avatar", uploadAvatar.single("avatar"), controller.uploadAvatar);
router.put("/change-password", controller.changePassword);
router.delete("/account", controller.deleteAccount);
router.get("/stats", controller.userStats);
router.put("/preferences", controller.updatePreferences);
router.get("/favorites", controller.list("favorites"));
router.post("/favorites", (req, res) => controller.addMovie("favorites", req, res));
router.delete("/favorites/:movieId", (req, res) => controller.removeMovie("favorites", req, res));
router.get("/watchlist", controller.list("watchlist"));
router.post("/watchlist", (req, res) => controller.addMovie("watchlist", req, res));
router.delete("/watchlist/:movieId", (req, res) => controller.removeMovie("watchlist", req, res));
router.get("/ratings", controller.list("ratings"));
router.post("/ratings", controller.rate);
router.get("/reviews", controller.list("reviews"));
router.post("/reviews", controller.addReview);
router.put("/reviews/:reviewId", controller.updateReview);
router.delete("/reviews/:reviewId", controller.deleteReview);
router.get("/reviews/movie/:movieId", controller.movieReviews);
router.get("/history", controller.history);
router.post("/history", controller.addHistory);
router.delete("/history", controller.clearHistory);
export default router;
